
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Complete language translations
const translations = {
  en: {
    'app.title': 'TERO',
    'app.subtitle': 'Triage and Emergency Routing Optimization',
    'paramedic': 'Paramedic',
    'language.select': 'Select Language',
    'location.title': 'Paramedic Location',
    'location.description': 'Current location and time information',
    'location.loading': 'Getting your location...',
    'location.current': 'Current Location',
    'location.gps': 'GPS Coordinates:',
    'location.error': 'Unable to access location. Please enable location services.',
    'location.updated': 'Location Updated',
    'location.success': 'Your current location has been successfully retrieved.',
    'location.required': 'Location Required',
    'location.enable': 'Please enable location services to get directions.',
    'hospitals.nearby': 'Nearby Hospitals',
    'hospitals.description': 'Real-time hospital locations based on your GPS coordinates',
    'hospitals.beds': 'Beds',
    'hospitals.icu': 'ICU',
    'hospitals.eta': 'Total Time',
    'hospitals.specialties': 'Specialties',
    'hospitals.matching': 'Hospital Matching',
    'hospitals.find': 'Find the best hospital for your patient',
    'hospitals.search': 'Search hospitals...',
    'hospitals.update': 'Update Data',
    'hospitals.recommended': 'Recommended Hospitals',
    'hospitals.ranked': 'Ranked by match to patient needs (within 30km)',
    'hospitals.none': 'No hospitals found within 30km radius',
    'hospitals.refresh': 'Refresh Hospital List',
    'hospitals.details': 'Hospital Details',
    'hospitals.map': 'Map View',
    'hospitals.contact': 'Contact Information',
    'hospitals.emergency': 'Emergency Department',
    'hospitals.trauma': 'Trauma Center with 24/7 emergency services',
    'hospitals.services': '24/7 emergency services available',
    'hospitals.route': 'Route to This Hospital',
    'hospitals.call': 'Call',
    'hospitals.directions': 'Directions',
    'hospitals.get.directions': 'Get Directions',
    'hospitals.opening.maps': 'Opening Maps',
    'hospitals.getting.directions': 'Getting directions to',
    'hospitals.open.google': 'Open in Google Maps',
    'hospitals.patient.matching': 'Patient Matching',
    'hospitals.prioritized': 'This hospital has been prioritized due to specialty match with the patient\'s needs:',
    'hospitals.proximity': 'This hospital is recommended based on proximity and available capacity for immediate care.',
    'hospitals.no.selection': 'No Hospital Selected',
    'hospitals.select.from.list': 'Select a hospital from the list to view details',
    'hospitals.wait': 'Please wait while we find nearby hospitals...',
    'hospitals.locations': 'Hospital Locations',
    'hospitals.navigate': 'View and navigate to recommended hospitals',
    'hospitals.type.government': 'Government',
    'hospitals.type.private': 'Private',
    'hospitals.type.trust': 'Trust',
    'hospitals.type.corporate': 'Corporate',
    'distance': 'Distance',
    'eta.label': 'ETA',
    'available.beds': 'Available Beds',
    'wait.time': 'Wait Time',
    'min': 'min',
    'km': 'km',
    'match': 'match',
    'hebbal.title': 'Recommended Hospitals',
    'hebbal.description': 'Best hospitals ranked by patient match',
    'error.map': 'Map Error',
    'error.loading': 'Failed to load the map. Please refresh the page.',
    'error.no.location': 'No location',
    'error.directions': 'Your current location is needed to get directions.',
    'error.opening.directions': 'Opening directions',
    'vitals.based': 'Match scores based on patient vital signs',
    'heart.rate': 'Heart Rate',
    'blood.pressure': 'BP',
    'oxygen.saturation': 'SpO2',
    'glasgow.coma': 'GCS',
    'refresh': 'Refresh',
    'location.error.title': 'Location Error',
    'use.location': 'Use my location',
    'getting.location': 'Getting location...',
    'select.city': 'Select city',
    'within.radius': 'within 30 km',
    'no.hospitals.found': 'No hospitals found',
    'no.hospitals.description': 'No hospitals found within 30km radius. Try selecting a different location.',
    'your.location': 'Your Location'
  },
  hi: {
    'app.title': 'टेरो',
    'app.subtitle': 'त्रिकोणीय और आपातकालीन मार्ग अनुकूलन',
    'paramedic': 'चिकित्सक',
    'language.select': 'भाषा चुनें',
    'location.title': 'चिकित्सक स्थान',
    'location.description': 'वर्तमान स्थान और समय की जानकारी',
    'location.loading': 'आपका स्थान प्राप्त कर रहे हैं...',
    'location.current': 'वर्तमान स्थान',
    'location.gps': 'जीपीएस निर्देशांक:',
    'location.error': 'स्थान तक पहुंचने में असमर्थ। कृपया स्थान सेवाएं सक्षम करें।',
    'location.updated': 'स्थान अपडेट किया गया',
    'location.success': 'आपका वर्तमान स्थान सफलतापूर्वक प्राप्त किया गया है।',
    'location.required': 'स्थान आवश्यक',
    'location.enable': 'दिशा-निर्देश प्राप्त करने के लिए कृपया स्थान सेवाएं सक्षम करें।',
    'hospitals.nearby': 'निकटतम अस्पताल',
    'hospitals.description': 'आपके जीपीएस निर्देशांक के आधार पर वास्तविक समय अस्पताल स्थान',
    'hospitals.beds': 'बिस्तर',
    'hospitals.icu': 'आईसीयू',
    'hospitals.eta': 'कुल समय',
    'hospitals.specialties': 'विशेषताएं',
    'hospitals.matching': 'अस्पताल मैचिंग',
    'hospitals.find': 'अपने रोगी के लिए सबसे अच्छा अस्पताल खोजें',
    'hospitals.search': 'अस्पताल खोजें...',
    'hospitals.update': 'डेटा अपडेट करें',
    'hospitals.recommended': 'अनुशंसित अस्पताल',
    'hospitals.ranked': 'रोगी की आवश्यकताओं के अनुसार रैंक किए गए (30 किमी के भीतर)',
    'hospitals.none': '30 किमी त्रिज्या में कोई अस्पताल नहीं मिला',
    'hospitals.refresh': 'अस्पताल सूची ताज़ा करें',
    'hospitals.details': 'अस्पताल विवरण',
    'hospitals.map': 'मानचित्र दृश्य',
    'hospitals.contact': 'संपर्क जानकारी',
    'hospitals.emergency': 'आपातकालीन विभाग',
    'hospitals.trauma': '24/7 आपातकालीन सेवाओं के साथ ट्रामा सेंटर',
    'hospitals.services': '24/7 आपातकालीन सेवाएं उपलब्ध',
    'hospitals.route': 'इस अस्पताल का मार्ग',
    'hospitals.call': 'कॉल करें',
    'hospitals.directions': 'दिशा-निर्देश',
    'hospitals.get.directions': 'दिशा-निर्देश प्राप्त करें',
    'hospitals.opening.maps': 'मानचित्र खोल रहे हैं',
    'hospitals.getting.directions': 'दिशा-निर्देश प्राप्त कर रहे हैं',
    'hospitals.open.google': 'गूगल मैप्स में खोलें',
    'hospitals.patient.matching': 'रोगी मैचिंग',
    'hospitals.prioritized': 'इस अस्पताल को रोगी की आवश्यकताओं से विशेषता मैच के कारण प्राथमिकता दी गई है:',
    'hospitals.proximity': 'यह अस्पताल निकटता और तत्काल देखभाल के लिए उपलब्ध क्षमता के आधार पर अनुशंसित है।',
    'hospitals.no.selection': 'कोई अस्पताल चयनित नहीं',
    'hospitals.select.from.list': 'विवरण देखने के लिए सूची से एक अस्पताल चुनें',
    'hospitals.wait': 'कृपया प्रतीक्षा करें जबकि हम निकटतम अस्पताल खोज रहे हैं...',
    'hospitals.locations': 'अस्पताल स्थान',
    'hospitals.navigate': 'अनुशंसित अस्पतालों को देखें और नेविगेट करें',
    'hospitals.type.government': 'सरकारी',
    'hospitals.type.private': 'निजी',
    'hospitals.type.trust': 'ट्रस्ट',
    'hospitals.type.corporate': 'कॉर्पोरेट',
    'distance': 'दूरी',
    'eta.label': 'अनुमानित समय',
    'available.beds': 'उपलब्ध बिस्तर',
    'wait.time': 'प्रतीक्षा समय',
    'min': 'मिनट',
    'km': 'किमी',
    'match': 'मैच',
    'hebbal.title': 'अनुशंसित अस्पताल',
    'hebbal.description': 'रोगी मैच द्वारा रैंक किए गए सर्वोत्तम अस्पताल',
    'error.map': 'मानचित्र त्रुटि',
    'error.loading': 'मानचित्र लोड करने में विफल। कृपया पृष्ठ ताज़ा करें।',
    'error.no.location': 'कोई स्थान नहीं',
    'error.directions': 'दिशा-निर्देश प्राप्त करने के लिए आपका वर्तमान स्थान आवश्यक है।',
    'error.opening.directions': 'दिशा-निर्देश खोल रहे हैं',
    'vitals.based': 'रोगी के महत्वपूर्ण संकेतों के आधार पर मैच स्कोर',
    'heart.rate': 'हृदय गति',
    'blood.pressure': 'बीपी',
    'oxygen.saturation': 'एसपीओ2',
    'glasgow.coma': 'जीसीएस',
    'refresh': 'ताज़ा करें',
    'location.error.title': 'स्थान त्रुटि',
    'use.location': 'मेरा स्थान उपयोग करें',
    'getting.location': 'स्थान प्राप्त कर रहे हैं...',
    'select.city': 'शहर चुनें',
    'within.radius': '30 किमी के भीतर',
    'no.hospitals.found': 'कोई अस्पताल नहीं मिला',
    'no.hospitals.description': '30 किमी त्रिज्या में कोई अस्पताल नहीं मिला। एक अलग स्थान चुनने का प्रयास करें।',
    'your.location': 'आपका स्थान'
  },
  kn: {
    'app.title': 'ಟೆರೋ',
    'app.subtitle': 'ತ್ರಿಕೋನ ಮತ್ತು ತುರ್ತು ಮಾರ್ಗ ಅನುಕೂಲತೆ',
    'paramedic': 'ವೈದ್ಯ',
    'language.select': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    'location.title': 'ವೈದ್ಯ ಸ್ಥಾನ',
    'location.description': 'ಪ್ರಸ್ತುತ ಸ್ಥಾನ ಮತ್ತು ಸಮಯದ ಮಾಹಿತಿ',
    'location.loading': 'ನಿಮ್ಮ ಸ್ಥಾನವನ್ನು ಪಡೆಯುತ್ತಿದ್ದೇವೆ...',
    'location.current': 'ಪ್ರಸ್ತುತ ಸ್ಥಾನ',
    'location.gps': 'ಜಿಪಿಎಸ್ ನಿರ್ದೇಶಾಂಕಗಳು:',
    'location.error': 'ಸ್ಥಾನವನ್ನು ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ಥಾನ ಸೇವೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.',
    'location.updated': 'ಸ್ಥಾನ ನವೀಕರಿಸಲಾಗಿದೆ',
    'location.success': 'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಾನವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪಡೆಯಲಾಗಿದೆ.',
    'location.required': 'ಸ್ಥಾನ ಅಗತ್ಯ',
    'location.enable': 'ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಲು ದಯವಿಟ್ಟು ಸ್ಥಾನ ಸೇವೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.',
    'hospitals.nearby': 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು',
    'hospitals.description': 'ನಿಮ್ಮ ಜಿಪಿಎಸ್ ನಿರ್ದೇಶಾಂಕಗಳ ಆಧಾರದ ಮೇಲೆ ನೈಜ-ಸಮಯದ ಆಸ್ಪತ್ರೆ ಸ್ಥಾನಗಳು',
    'hospitals.beds': 'ಹಾಸಿಗೆಗಳು',
    'hospitals.icu': 'ಐಸಿಯು',
    'hospitals.eta': 'ಒಟ್ಟು ಸಮಯ',
    'hospitals.specialties': 'ವಿಶೇಷತೆಗಳು',
    'hospitals.matching': 'ಆಸ್ಪತ್ರೆ ಹೊಂದಾಣಿಕೆ',
    'hospitals.find': 'ನಿಮ್ಮ ರೋಗಿಗೆ ಅತ್ಯುತ್ತಮ ಆಸ್ಪತ್ರೆಯನ್ನು ಹುಡುಕಿ',
    'hospitals.search': 'ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ...',
    'hospitals.update': 'ಡೇಟಾ ನವೀಕರಿಸಿ',
    'hospitals.recommended': 'ಶಿಫಾರಸು ಮಾಡಿದ ಆಸ್ಪತ್ರೆಗಳು',
    'hospitals.ranked': 'ರೋಗಿಯ ಅಗತ್ಯಗಳಿಗೆ ಹೊಂದಾಣಿಕೆಯಿಂದ ಶ್ರೇಣೀಕೃತ (30 ಕಿಮೀ ಒಳಗೆ)',
    'hospitals.none': '30 ಕಿಮೀ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಯಾವುದೇ ಆಸ್ಪತ್ರೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'hospitals.refresh': 'ಆಸ್ಪತ್ರೆ ಪಟ್ಟಿಯನ್ನು ನವೀಕರಿಸಿ',
    'hospitals.details': 'ಆಸ್ಪತ್ರೆ ವಿವರಗಳು',
    'hospitals.map': 'ನಕ್ಷೆ ವೀಕ್ಷಣೆ',
    'hospitals.contact': 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
    'hospitals.emergency': 'ತುರ್ತು ವಿಭಾಗ',
    'hospitals.trauma': '24/7 ತುರ್ತು ಸೇವೆಗಳೊಂದಿಗೆ ಆಘಾತ ಕೇಂದ್ರ',
    'hospitals.services': '24/7 ತುರ್ತು ಸೇವೆಗಳು ಲಭ್ಯ',
    'hospitals.route': 'ಈ ಆಸ್ಪತ್ರೆಗೆ ಮಾರ್ಗ',
    'hospitals.call': 'ಕರೆ ಮಾಡಿ',
    'hospitals.directions': 'ದಿಕ್ಕುಗಳು',
    'hospitals.get.directions': 'ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ',
    'hospitals.opening.maps': 'ನಕ್ಷೆಗಳನ್ನು ತೆರೆಯುತ್ತಿದೆ',
    'hospitals.getting.directions': 'ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯುತ್ತಿದೆ',
    'hospitals.open.google': 'ಗೂಗಲ್ ನಕ್ಷೆಗಳಲ್ಲಿ ತೆರೆಯಿರಿ',
    'hospitals.patient.matching': 'ರೋಗಿ ಹೊಂದಾಣಿಕೆ',
    'hospitals.prioritized': 'ರೋಗಿಯ ಅಗತ್ಯಗಳೊಂದಿಗೆ ವಿಶೇಷತೆ ಹೊಂದಾಣಿಕೆಯ ಕಾರಣ ಈ ಆಸ್ಪತ್ರೆಗೆ ಆದ್ಯತೆ ನೀಡಲಾಗಿದೆ:',
    'hospitals.proximity': 'ಈ ಆಸ್ಪತ್ರೆಯನ್ನು ಸಾಮೀಪ್ಯ ಮತ್ತು ತಕ್ಷಣದ ಆರೈಕೆಗಾಗಿ ಲಭ್ಯವಿರುವ ಸಾಮರ್ಥ್ಯದ ಆಧಾರದ ಮೇಲೆ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.',
    'hospitals.no.selection': 'ಯಾವುದೇ ಆಸ್ಪತ್ರೆ ಆಯ್ಕೆಯಾಗಿಲ್ಲ',
    'hospitals.select.from.list': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಪಟ್ಟಿಯಿಂದ ಆಸ್ಪತ್ರೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'hospitals.wait': 'ನಾವು ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕುತ್ತಿರುವಾಗ ದಯವಿಟ್ಟು ಕಾಯಿರಿ...',
    'hospitals.locations': 'ಆಸ್ಪತ್ರೆ ಸ್ಥಾನಗಳು',
    'hospitals.navigate': 'ಶಿಫಾರಸು ಮಾಡಿದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ನ್ಯಾವಿಗೇಟ್ ಮಾಡಿ',
    'hospitals.type.government': 'ಸರ್ಕಾರಿ',
    'hospitals.type.private': 'ಖಾಸಗಿ',
    'hospitals.type.trust': 'ಟ್ರಸ್ಟ್',
    'hospitals.type.corporate': 'ಕಾರ್ಪೊರೇಟ್',
    'distance': 'ದೂರ',
    'eta.label': 'ಇಟಿಎ',
    'available.beds': 'ಲಭ್ಯವಿರುವ ಹಾಸಿಗೆಗಳು',
    'wait.time': 'ಕಾಯುವ ಸಮಯ',
    'min': 'ನಿಮಿಷ',
    'km': 'ಕಿಮೀ',
    'match': 'ಹೊಂದಾಣಿಕೆ',
    'hebbal.title': 'ಶಿಫಾರಸು ಮಾಡಿದ ಆಸ್ಪತ್ರೆಗಳು',
    'hebbal.description': 'ರೋಗಿಯ ಹೊಂದಾಣಿಕೆಯಿಂದ ಶ್ರೇಣೀಕೃತ ಅತ್ಯುತ್ತಮ ಆಸ್ಪತ್ರೆಗಳು',
    'error.map': 'ನಕ್ಷೆ ದೋಷ',
    'error.loading': 'ನಕ್ಷೆಯನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಪುಟವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ.',
    'error.no.location': 'ಯಾವುದೇ ಸ್ಥಾನವಿಲ್ಲ',
    'error.directions': 'ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಾನ ಅಗತ್ಯ.',
    'error.opening.directions': 'ದಿಕ್ಕುಗಳನ್ನು ತೆರೆಯುತ್ತಿದೆ',
    'vitals.based': 'ರೋಗಿಯ ಪ್ರಾಣ ಸಂಕೇತಗಳ ಆಧಾರದ ಮೇಲೆ ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್‌ಗಳು',
    'heart.rate': 'ಹೃದಯ ಬಡಿತ',
    'blood.pressure': 'ಬಿಪಿ',
    'oxygen.saturation': 'ಎಸ್‌ಪಿಒ2',
    'glasgow.coma': 'ಜಿಸಿಎಸ್',
    'refresh': 'ನವೀಕರಿಸಿ',
    'location.error.title': 'ಸ್ಥಾನ ದೋಷ',
    'use.location': 'ನನ್ನ ಸ್ಥಾನವನ್ನು ಬಳಸಿ',
    'getting.location': 'ಸ್ಥಾನವನ್ನು ಪಡೆಯುತ್ತಿದೆ...',
    'select.city': 'ನಗರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'within.radius': '30 ಕಿಮೀ ಒಳಗೆ',
    'no.hospitals.found': 'ಯಾವುದೇ ಆಸ್ಪತ್ರೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'no.hospitals.description': '30 ಕಿಮೀ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಯಾವುದೇ ಆಸ್ಪತ್ರೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಬೇರೆ ಸ್ಥಳವನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ಪ್ರಯತ್ನಿಸಿ.',
    'your.location': 'ನಿಮ್ಮ ಸ್ಥಾನ'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'hi', 'kn'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
